import { createRoot } from 'react-dom/client'
import './styles.css'
import { Logo } from '@pmndrs/branding'
import { App } from './App'

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

function Root() {
  return (
    <>
      <App />
      <div style={{ position: 'absolute', pointerEvents: 'none', top: 0, left: 0, width: '100vw', height: '100vh' }}>
         <div style={{ position: 'absolute', top: 40, left: 40, fontSize: '13px' }}><a href={window.APP_CONFIG.Next}>*.mydream42.com</a></div>
        <div style={{ position: 'absolute', bottom: 40, right: 40, fontSize: '13px' }}>nenaneffati.com</div>
        <div style={{ position: 'absolute', bottom: 40, left: 40, fontSize: '13px' }}>beer.mydream42.com</div>
      </div>{' '}
    </>
  )
}

createRoot(document.getElementById('root')).render(<Root />)
